//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_track_list_extended
    {
        public int TrackId { get; set; }
        public string Track { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string Album { get; set; }
        public int MediaTypeId { get; set; }
        public string MediaType { get; set; }
        public Nullable<int> GenreId { get; set; }
        public string Genre { get; set; }
        public string Composer { get; set; }
        public int Milliseconds { get; set; }
        public Nullable<int> Bytes { get; set; }
        public string Artist { get; set; }
    }
}
